Allow emojis in the GitHub worker
python-discord/workers pull request #4
Opened 2021-04-19 17:10 UTC by Akarys42

This should make the GitHub filter worker lookup a new `emojis` namespace for how to translate literal emojis such as `:shipit:` to their in-server version.

Not tested yet, I can't really make the worker work.

2021-04-19 17:22 UTC, jb3 requested changes
Looks good, a few minor JS things.

We'll need to add a KV binding to `EMOJIS`, the ID is `183f1ae82b8d458f983e39eb2c99fa9a`.

It should be this key in the `wrangler.toml`:
```toml
kv_namespaces = [
  { binding = "EMOJIS", id = "183f1ae82b8d458f983e39eb2c99fa9a", preview_id = "183f1ae82b8d458f983e39eb2c99fa9a" }
]
```

2021-04-19 17:22 UTC, jb3 commented on github-filter-worker/src/bindings.d.ts
> +    const emojis: KVNamespace
Should be uppercase.
```suggestion
    const EMOJIS: KVNamespace
```

2021-04-19 17:22 UTC, jb3 commented on github-filter-worker/src/index.ts
> +  let value = await emojis.get(name)
```suggestion
  let value = await EMOJIS.get(name)
```

2021-04-19 17:22 UTC, jb3 commented on github-filter-worker/src/index.ts
> +  return value === null ? value : name
`null` is falsey, so explicit comparison is not required:
```js
> let val = null;
undefined
> val ? "a" : "b"
'b'
> val = "abcdef"
'abcdef'
> val ? "a" : "b"
'a'
```
```suggestion
  return value ? value : name
```

2021-04-19 17:22 UTC, jb3 commented on github-filter-worker/src/index.ts
> +          function(p1) {return lookupEmoji(p1)}
```suggestion
          (match) =>  lookupEmoji(match)
```

2021-04-20 16:36 UTC, jb3 approved these changes
Golden. :shipit:

2021-04-20 16:37 UTC, jb3 approved these changes
Hol up! ![err](https://media.discordapp.net/attachments/635950537262759947/834105406430117949/Screenshot_2021-04-20_at_17.37.00.png)

2021-04-20 16:58 UTC, jb3 commented
:shipit:

2021-04-20 17:25 UTC, Akarys42 commented
🍋 :shipit:

2021-04-20 17:26 UTC, jb3 submitted a review, later dismissed
Marvellous, so... let's :shipit:.

2021-04-20 19:30 UTC, jb3 commented
Test :shipit:

2021-04-20 19:38 UTC, jb3 commented
:shipit:

2021-04-20 19:39 UTC, jb3 approved these changes

2021-04-20 19:39 UTC, merged